version: "3.8"

services:
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

  trino:
    image: trinodb/trino
    ports:
      - "8080:8080"

  openmetadata:
    image: openmetadata/server:latest
    ports:
      - "8585:8585"

  ranger:
    image: apache/ranger-admin
    ports:
      - "6080:6080"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
